import { Josefin_Sans, Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Header from "@/components/Header/Header";

//Font Awesome Icon
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Footer from "@/components/Footer/Footer";
import Footer2 from "@/components/Footer/Footer2";
import Scroll from "@/components/common/Scroll";
config.autoAddCss = false;

const josefin = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin",
});

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${josefin.variable} ${cormorant.className} antialiased`}
      >
        <Header />
        <Navbar />
        {children}
        <Footer />
        <Footer2 />
        <Scroll />
      </body>
    </html>
  );
}
